#placeholder for error message definition
com.vmware.vsan.common.fault.error = "Se produjo un error inesperado en: {reason}."
com.vmware.vsan.health.msg.host.daemon.unhealthy = "El daemon de host no se está ejecutando."
com.vmware.vsan.health.msg.silent.setting.error = "Error de configuración de comprobación de estado silenciosa: {reason}."
com.vmware.vsan.health.msg.silent.testid.invalid = "Identificador de comprobación de estado silenciosa no válido: {testId}."
com.vmware.vsan.health.msg.systemerror = "Se produjo un error general del sistema: {reason}."
com.vmware.vsan.health.msg.drsmode = "DRS no está habilitado o no está en modo totalmente automatizado."
com.vmware.vsan.health.msg.install.alreadyrunning = "Ya hay una tarea de instalación/desinstalación para este clúster en ejecución."
com.vmware.vsan.health.msg.task.cancelled  = "El usuario canceló la tarea de estado de vSAN."
com.vmware.vsan.health.msg.InvalidHealthCheckInterval = "Se encontró una configuración de intervalo de comprobación de estado no válida (negativa)."
com.vmware.vsan.health.msg.sendVsanTelemetryfailed = "No se pudo enviar la telemetría de vSAN."
com.vmware.vsan.health.msg.CEIPDisabled = "No se pudo enviar la telemetría de vSAN debido a que la opción del Programa de mejora de la experiencia de cliente está deshabilitada."
com.vmware.vsan.health.msg.InvalidVsanTelemetryProxy = "La configuración de proxy no es válida."
com.vmware.vsan.health.msg.hcldecodefailed = "No se pudo decodificar la base de datos de HCL."
com.vmware.vsan.health.msg.hclupdatefailed = "No se pudo reemplazar la base de datos de HCL anterior con la nueva."
com.vmware.vsan.health.msg.hcloutdated = "La base de datos de HCL de vSAN está desactualizada."
com.vmware.vsan.health.msg.hclmalformed = "La base de datos de HCL de vSAN incluye contenido con formato incorrecto."
com.vmware.vsan.health.msg.fixobjectsfailed = "No se pudo corregir el objeto de inmediato."
com.vmware.vsan.health.msg.attachtosrfailed = "No se pudo adjuntar el paquete de soporte a SR."
com.vmware.vsan.health.msg.storageloadtestfailed = "No se pudo ejecutar la prueba de carga de almacenamiento de vSAN."
com.vmware.vsan.health.msg.privilegecheckfailed = "No se pudo aplicar la comprobación de privilegio de VC."
com.vmware.vsan.health.msg.eamfailed = "No se pudieron instalar los VIB en los hosts del clúster de VC con EAM."
com.vmware.vsan.health.msg.precheck.version.fail = "Las versiones de los hosts ESXi no son coherentes."
com.vmware.vsan.health.msg.rebalancefailed = "No se pudo redistribuir el clúster de vSAN."
com.vmware.vsan.health.msg.stoprebalancefailed = "No se pudo detener la redistribución del clúster de vSAN."
com.vmware.vsan.health.msg.rebalance.fail = "La operación no se admite debido a que la redistribución proactiva en segundo plano está habilitada."
com.vmware.vsan.health.msg.precheck.drs.fail = "El DRS de clúster no está totalmente automatizado."
com.vmware.vsan.health.msg.precheck.eam.fail = "El servicio EAM no está disponible."
com.vmware.vsan.health.msg.precheck.uninstallstate.uninstallrunning.fail = "El proceso de desinstalación está en curso; espere hasta que se complete la desinstalación."
com.vmware.vsan.health.msg.precheck.uninstallstate.installrunning.fail = "La desinstalación no se puede realizar cuando el proceso de instalación está en curso; espere hasta que se complete la instalación."
com.vmware.vsan.health.msg.precheck.uninstallstate.completed.fail = "vSAN Health Service ya se desinstaló."
com.vmware.vsan.health.msg.host.novsandatastore.fail = "No se puede encontrar el almacén de datos de vSAN en el host."
com.vmware.vsan.health.msg.host.novsandatastoreproperty.fail = "No se pueden encontrar las propiedades del almacén de datos de vSAN en el host."
com.vmware.vsan.health.msg.host.notconnected = "El host no está en estado conectado."
com.vmware.vsan.health.msg.host.runtime.error = "Se produjo un error desconocido en el estado de vSAN. Motivo: {causeMessage}."
com.vmware.vsan.health.msg.list.kmxa.provider.error = "No se pueden recuperar los detalles del proveedor de claves en el host.{causeMessage}."
com.vmware.vsan.health.msg.host.httperror = "Se produjo un error de comunicación de host en el estado de vSAN. Motivo: {causeMessage}."
com.vmware.vsan.health.msg.invalidrequest = "Solicitud no válida (¿está instalada la versión correcta del estado de vSAN?). "
com.vmware.vsan.health.msg.storageloadtest.runvmdktest.fail = "No se pudo ejecutar la prueba de carga de almacenamiento para el VMDK {vmdknum}. Motivo: {causeMessage}."
com.vmware.vsan.health.msg.storageloadtest.preparevmdk.fail = "No se pudo crear el VMDK para la prueba de carga de almacenamiento. Motivo: {causeMessage}."
com.vmware.vsan.health.msg.storageloadtest.cleanvmdk.fail = "No se pudo limpiar el VMDK en la prueba de carga de almacenamiento. Motivo: {causeMessage}."
com.vmware.vsan.health.msg.createvm.novsandatastore.fail = "No se puede encontrar el almacén de datos de vSAN en el host."
com.vmware.vsan.health.msg.host.kmsconnection.fail = "No se pudo establecer comunicación con el servidor de administración de claves."
com.vmware.vsan.health.msg.host.kmsconnection.auth = "No se pudo realizar la autenticación de usuario en el servidor de administración de claves."
com.vmware.vsan.health.msg.host.kmsconnection.timeout = "Se agotó el tiempo de espera de la conexión en el servidor de administración de claves."
com.vmware.vsan.health.msg.vc.kmsconnection.kmsclustermissing = "No se encuentra la configuración de clúster del servidor de administración de claves."
com.vmware.vsan.health.msg.kmsconnection.runtime.error = "No se pudo comprobar el estado de conexión del servidor de administración de claves. Motivo: {causeMessage}."
com.vmware.vsan.health.msg.vc.kmsconnection.awskmssvcunreachable = "No se puede acceder al servicio AWS KMS."
com.vmware.vsan.health.msg.vc.kmsconnection.awskmscmknotinenable = "La CMK que el clúster utilizó no tiene el estado Habilitado."
com.vmware.vsan.health.msg.queryhealth.gethostsinfo.fail = "No se pudieron obtener los hosts ni la información de VC."
com.vmware.vsan.health.msg.queryhealth.timeout = "Se agotó el tiempo de espera al consultar el resumen de estado del clúster."
com.vmware.vsan.health.msg.queryhealth.generalerror = "Se produjo un error general al consultar el resumen de estado del clúster."
com.vmware.vsan.health.msg.queryhealth.perspectivecomputeonlyerror = "Perspectiva no admitida para el clúster de proceso de la malla de HCI."
com.vmware.vsan.health.msg.queryencryptionhealth.timeout = "Se agotó el tiempo de espera al consultar el estado de cifrado del clúster."
vsan.clomd.stat.error = "No se pudo obtener la información de estadísticas de clomd de vSAN."
vsan.clomd.invalid.output = "Salida no válida al obtener las estadísticas de clomd de vSAN."
vsan.clomd.timeout = "Se agotó el tiempo de espera al intentar conectarse al proceso clomd de vSAN"
com.vmware.vsan.health.msg.downloadhclfilefailed.title = "No se pudieron descargar uno o varios archivos de HCL."
com.vmware.vsan.health.msg.downloadhclfilefailed.failed = "No se pudo descargar el archivo de {sha1}. Motivo: {reason}."
com.vmware.vsan.health.msg.downloadhclfilefailed.notinhcl = "La suma de comprobación proporcionada no coincide con ningún registro de la base de datos."
com.vmware.vsan.health.msg.downloadhclfilefailed.wrongfile = "El contenido del archivo descargado de {url} no es el que se esperaba. Esto podría deberse al entorno de red. Intente descargarlo de nuevo."
com.vmware.vsan.health.msg.downloadhclfilefailed.exception = "No se pudo descargar el archivo de {url}. Motivo: {reason}."
com.vmware.vsan.health.msg.downloadinstalltool.generic = "No se pudo descargar ni instalar la herramienta del proveedor."
com.vmware.vsan.health.hcllib.gethclconstraint.failed = "No se pudo obtener la restricción de HCL."
com.vmware.vsan.health.hcllib.releaserecommendation.notsupported = "La versión {release} no es compatible con vSAN."
com.vmware.vsan.health.hcllib.setvcgmapping.failed = "No se pudieron establecer las asignaciones de los dispositivos de hardware con las entradas de la VCG (Guía de compatibilidad de VMware) para vSAN."
com.vmware.vsan.health.getvsaneligiblediskhcl.failed = "No se pudo obtener la información de HCL para discos aptos de vSAN."
com.vmware.vsan.health.msg.host.pcap.unicast.failed = "El host del modo de unidifusión no admite la observación de paquetes de multidifusión."
com.vmware.vsan.health.msg.host.pcap.timeout = "Se agotó el tiempo de espera al observar paquetes de multidifusión."
com.vmware.vsan.clustermgmt.msg.remediationfailed = "No se pudo corregir la configuración de vSAN."
com.vmware.vsan.clustermgmt.msg.addhostfailed = "No se pudo agregar el host al clúster."
com.vmware.vsan.clustermgmt.msg.reconnecthostfailed = "No se pudo volver a conectar el host al clúster."
com.vmware.vsan.clustermgmt.msg.removehostfailed = "No se pudo quitar el host del clúster."
com.vmware.vsan.clustermgmt.msg.reconfigurefailed = "No se pudo volver a configurar el clúster de vSAN."
com.vmware.vsan.perfsvc.fault.precheck.emptycluster = "No se puede continuar con un clúster vacío."
com.vmware.vsan.clustermgmt.msg.destroyfailed = "No se pudo destruir el clúster de vSAN."
com.vmware.vsan.perfsvc.fault.precheck.networkunhealth = "La red tiene particiones o hosts desconectados. Compruebe el estado de mantenimiento la red."
com.vmware.vsan.perfsvc.fault.parseprofile = "No se pudo analizar ni validar el perfil de directiva de almacenamiento especificado."
com.vmware.vsan.perfsvc.fault.createstatsdb = "No pudo habilitarse el servicio de rendimiento de vSAN."
com.vmware.vsan.perfsvc.fault.deletestatsdb = "No pudo deshabilitarse el servicio de rendimiento de vSAN."
com.vmware.vsan.perfsvc.fault.filenonvmodl = "El archivo JSON proporcionado no se puede traducir a Vmodl."
com.vmware.vsan.perfsvc.fault.masternotfound = "No se encuentra el principal de estadísticas en el clúster."
com.vmware.vsan.perfsvc.fault.notaccessible = "No se puede acceder al servicio de rendimiento en el host. Puede que el host sea inalcanzable o que la versión del host no sea compatible."
com.vmware.vsan.perfsvc.fault.statsobject.invalidstate = "No se puede eliminar el objeto de estadísticas en el estado actual. Puede que el principal de estadísticas esté en modo de mantenimiento."
com.vmware.vsan.perfsvc.fault.perfanalytics = "El análisis del rendimiento no es compatible con hosts ESX independientes."
com.vmware.vsan.perfsvc.fault.queryexceedstimerange = "La duración de la consulta supera el umbral."
com.vmware.vsan.perfsvc.fault.queryperf.timeout = "Se agotó el tiempo de espera de la operación. Ningún dato de rendimiento del almacén de datos de vSAN respondió en el tiempo esperado (40 segundos)."
com.vmware.vsan.perfsvc.fault.queryperf.queryrange = "Argumento no válido. La duración entre startTime y endTime no debe ser superior a 24 horas."
com.vmware.vsan.perfsvc.fault.queryperf.wildcardlimit = "Argumento no válido. Solo se admite una consulta comodín en las especificaciones de la consulta."
com.vmware.vsan.perfsvc.fault.queryperf.wildcardqueryrange = "Argumento no válido. La duración entre startTime y endTime para la consulta comodín no debe ser superior a 1 hora."
com.vmware.vsan.perfsvc.fault.queryperf.ioinsighthistowildcard = "La consulta de histograma de IOInsight no admite las consultas comodín."
com.vmware.vsan.perfsvc.fault.queryperf.ioinsightmultientities = "El número de identificadores de nodo para la consulta de varias entidades de IOInsight no debe ser superior a {size}."
com.vmware.vsan.perfsvc.fault.queryperf.multientitiesquery = "Argumento no válido. La consulta de varias entidades solo admite la consulta de estadísticas de IOInsight y solo permite una especificación en las especificaciones de consulta."
com.vmware.vsan.perfsvc.fault.queryperf.vsanisnotenabled = "No se pueden consultar los datos de rendimiento de vSAN del clúster porque vSAN no está habilitado en él."
com.vmware.vsan.perfsvc.fault.statsdb.notfound = "No se encontró el objeto de base de datos de estadísticas de vSAN."
com.vmware.vsan.perfsvc.fault.timerange.name = "El nombre de TimeRange no debe quedar vacío ni tener más de 256 caracteres."
com.vmware.vsan.perfsvc.fault.timerange.name.duplicate = "El nombre de TimeRange es un duplicado."
com.vmware.vsan.perfsvc.fault.timerange.name.exist = "El nombre de TimeRange ya existe."
com.vmware.vsan.perfsvc.fault.timerange.time = "El valor de startTime debe ser inferior al de endTime, y la duración entre startTime y endTime no debe ser superior a 24 horas."
com.vmware.vsan.perfsvc.fault.configlimit = "La información que se desea guardar supera el límite máximo de capacidad."
com.vmware.vsan.perfsvc.fault.cmmds.subscription.timeout = "Se agotó el tiempo de espera para suscribir CMMDS."
com.vmware.vsan.perfsvc.fault.cmmds.subscription.general = "No se pudo suscribir CMMDS."
com.vmware.vsan.perfsvc.fault.unablefetchresult = "No se puede recuperar el resultado del diagnóstico."
com.vmware.vsan.perfsvc.fault.unablegeneratedata = "No se pueden generar los datos para el diagnóstico del rendimiento."
com.vmware.vsan.perfsvc.fault.feedbacksubmissionfailure = "Se produjo un error al enviar comentarios de PerfAnalytics a phonehome."
com.vmware.vsan.perfsvc.fault.phonehomeintegrationfailure = "No se pudo establecer la conexión con PhoneHome."
com.vmware.vsan.perfsvc.fault.phonehomeresponsefailure = "No se recibió ninguna actualización de PhoneHome."
com.vmware.vsan.perfsvc.fault.ceipdisabled = "Error al comprobar CEIP."
com.vmware.vsan.perfsvc.fault.nonjsonformat = "Se recibieron datos en formato no JSON de phonehome."
com.vmware.vsan.perfsvc.fault.nonvmodlformat = "Los datos JSON recibidos de phonehome no se pueden traducir a Vmodl."
com.vmware.vsan.perfsvc.fault.ioinsight.missedcluster = "Se requiere un clúster para la operación de IOInsight."
com.vmware.vsan.perfsvc.fault.ioinsight.invalidduration = "La duración válida de la ejecución de IOInsight está comprendida entre 1 minuto y 24 horas."
com.vmware.vsan.perfsvc.fault.ioinsight.invalidtarget = "Los hosts o las máquinas virtuales de destino no son válidos."
com.vmware.vsan.perfsvc.fault.ioinsight.alreadyrunning = "IOInsight ya se está ejecutando en el host."
com.vmware.vsan.perfsvc.fault.ioinsight.notrunning = "IOInsight no se está ejecutando en el host."
com.vmware.vsan.perfsvc.fault.ioinsight.start.failed = "No se pudo iniciar IOInsight en el host."
com.vmware.vsan.perfsvc.fault.ioinsight.append.failed = "No se pudo anexar el destino a IOInsight."
com.vmware.vsan.perfsvc.fault.ioinsight.delete.failed = "No se pudo eliminar el destino de IOInsight."
com.vmware.vsan.perfsvc.fault.ioinsight.invalidinfo = "La información de la instancia de IOInsight especificada no es válida."
com.vmware.vsan.perfsvc.fault.ioinsight.stop.exception = "Se produjo una excepción inesperada al detener IOInsight."
com.vmware.vsan.perfsvc.fault.ioinsight.query.failed = "No se pudo consultar el estado de IOInsight en el host."
com.vmware.vsan.perfsvc.fault.ioinsight.alreadyexists = "Ya existe una instancia de IOInsight con el nombre especificado."
com.vmware.vsan.perfsvc.fault.ioinsight.notexist = "La instancia de IOInsight especificada no existe."
com.vmware.vsan.perfsvc.fault.ioinsight.notinrunningstate = "La instancia de IOInsight especificada no está en estado de ejecución."
com.vmware.vsan.perfsvc.fault.ioinsight.internalerror = "Error interno de IOInsight."
com.vmware.vsan.perfsvc.fault.ioinsight.wildcardsizetoolarge = "Consulta de comodín no válida. El número de entidad es demasiado grande; especifique entityId en la especificación de consulta."
com.vmware.vsan.perfsvc.fault.topn.vsanisnotenabled = "No se pueden recuperar los contribuidores principales de vSAN del clúster porque vSAN no está habilitado en él."
com.vmware.vsan.health.msg.getproactiverebalanceinfo.error = "No se pudo obtener la información de redistribución proactiva de vSAN."
com.vmware.vsan.health.msg.getproactiverebalanceinfo.invalid.output = "Salida no válida al obtener la información de redistribución proactiva de vSAN."
com.vmware.vsan.health.msg.clomd.connecterror = "No se puede conectar con el proceso clomd y posiblemente esté inactivo."
com.vmware.vsan.health.msg.clomd.sendcmderror = "No se pudo enviar el comando a clomd."
com.vmware.vsan.health.msg.clomd.resulterror = "No se pudo obtener el resultado del comando clomd."
com.vmware.vsan.health.msg.clomd.networkerror = "No se pudo ejecutar el comando clomd debido a un error de socket de la red."
com.vmware.vsan.health.msg.clomd.unknownerror = "No se pudo ejecutar el comando clomd debido a un error desconocido."
com.vmware.vsan.health.msg.getrebalanceinfo.error = "No se pudo obtener la información de redistribución de vSAN."
com.vmware.vsan.health.msg.invaliddiskuuid.error = "Se obtuvo un UUID de disco no válido para el estado de redistribución de vSAN."
com.vmware.vsan.health.msg.invalidrebalancestatus.error = "Estado no válido al obtener la información de redistribución de vSAN."
com.vmware.vsan.health.msg.getrebalanceinfo.invalid.output = "Salida no válida al obtener la información de redistribución de vSAN."
com.vmware.vsan.health.msg.createvm.error = "Error al ejecutar la prueba de creación de máquina virtual."
com.vmware.vsan.perfsvc.fault.vsanperfconfig.methodnotfound = "No se admite la operación. Algunos hosts ejecutan versiones de software inferiores en el clúster."
com.vmware.vsan.perfsvc.fault.analytics.eneityrefidlength = "El identificador de referencia de entidad de rendimiento debe ser un número entre 1 y 256."
com.vmware.vsan.perfsvc.fault.analytics.invalidrefidtype = "El tipo de identificador de referencia de entidad de rendimiento no es válido."
com.vmware.vsan.easyinstall.fault.specmismatch  = "El plan de migración no coindice con la migración que se ha realizado. Vuelva a intentarlo con un plan de migración actualizado."
com.vmware.vsan.easyinstall.fault.invalidhosts = "Se encontraron hosts no válidos durante la migración. Verifique si están en el clúster especificado."
com.vmware.vsan.easyinstall.fault.invalidvswitch = "Se encontró un vSwitch no válido durante la migración. Verifique si el vSwitch se encuentra en todos los hosts."
com.vmware.vsan.health.msg.performonlinehealthcheck.title = "No se pudo realizar la comprobación en línea del estado de vSAN. Motivo: {reason}."
com.vmware.vsan.health.msg.performonlinehealthcheck.ceiperror = "CEIP está deshabilitado."
com.vmware.vsan.health.msg.performonlinehealthcheck.nonvsanerror = "Esto no es un clúster habilitado de vSAN."
com.vmware.vsan.health.msg.performonlinehealthcheck.connecterror = "No se pueden recopilar ni enviar datos al servicio PhoneHome de VMware."
com.vmware.vsan.health.msg.performonlinehealthcheck.vcnetworkerror = "vSAN deshabilitó el acceso a Internet de vCenter."
com.vmware.vsan.easyinstall.fault.failmigrationwithvms  = "No se realizará la migración porque se encontraron algunas máquinas virtuales inaccesibles o huérfanas: {vms}."
com.vmware.vsan.easyinstall.fault.failmigrationwithhosts  = "No se realizará la migración porque se encontraron algunos hosts inaccesibles o huérfanos: {hosts}."
com.vmware.vsan.easyinstall.fault.failmigrationwithpre60hosts  = "No se realizará la migración porque hay algunos hosts con una versión anterior a 6.0: {hosts}."
com.vmware.vsan.easyinstall.fault.failmigrationwithpre65ep2hosts  = "No se realizará la migración porque se han encontrado infraVM en los hosts con una versión anterior a 6.5.0d: {hosts}."
com.vmware.vsan.easyinstall.fault.failmigrationwithissues  = "No se realizará la migración debido a problemas."
com.vmware.vsan.easyinstall.fault.querytimeout = "Se agotó el tiempo de espera al consultar la información de HCL."
com.vmware.vsan.easyinstall.fault.reboottimeout = "Se agotó el tiempo de espera de {minutes} minutos para el reinicio del host. Puede que se deba comprobar el host y solucionar los posibles problemas."
com.vmware.vsan.health.msg.queryhealthsummaryfailed.title = "No se pudo realizar una comprobación de estado del clúster de vSAN."
com.vmware.vsan.health.msg.querynetworkperffailed.title = "No se pudo realizar la prueba de rendimiento de la red en {cluster}"
com.vmware.vsan.health.msg.querynetworkperffailed.nohosterror = "{cluster} no tiene ningún host para realizar la prueba de red."
com.vmware.vsan.health.msg.queryhealthsummary.iswitnessnode = "La comprobación de estado del clúster de vSAN no se admite en el nodo testigo"
com.vmware.vsan.fileservice.fault.enableerror = "No se pudo habilitar el servicio de archivos de vSAN."
com.vmware.vsan.fileservice.fault.disableerror = "No se pudo deshabilitar el servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.remediationerror = "Error al corregir el servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.downloadovferror = "No se pudo descargar el OVF del servicio de archivos de vSAN."
com.vmware.vsan.fileservice.fault.ovfalreadyexistserror = "Ya se ha descargado la versión {version} del OVF del servicio de archivos de vSAN en este vCenter."
com.vmware.vsan.fileservice.fault.ovflookuperror = "No se encuentra la versión especificada del OVF del servicio de archivos de vSAN."
com.vmware.vsan.fileservice.fault.enablefsonhost = "No se puede habilitar el servicio de archivos de vSAN en el host {host}."
com.vmware.vsan.fileservice.fault.notenabled = "El servicio de archivos de vSAN todavía no está habilitado en este host."
com.vmware.vsan.fileservice.fault.createdomainfailure = "No se puede crear un dominio para el servicio de archivos de vSAN."
com.vmware.vsan.fileservice.fault.removedomain = "No se puede eliminar un dominio para el servicio de archivos de vSAN."
com.vmware.vsan.fileservice.fault.reconfiguredomainfailure = "No se puede reconfigurar el dominio para el servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.sharenotfound = "No se puede encontrar el recurso compartido de archivos {name} después de crearlo"
com.vmware.vsan.fileservice.fault.queryshares = "No se pudieron consultar los recursos compartidos de archivo del servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.createshare = "No se pudo crear el recurso compartido de archivos de vSAN"
com.vmware.vsan.fileservice.fault.removeshare = "No se pudo quitar el recurso compartido de archivos de vSAN"
com.vmware.vsan.fileservice.fault.queryconfig = "No se pudo consultar la configuración del servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.configconversionerror = "No se pudo convertir el formato de configuración del servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.removeshare.noentity = "No se proporcionó el nombre o el UUID del recurso compartido para quitarlo"
com.vmware.vsan.fileservice.fault.nocapability = "No se encuentran capacidades de host en los hosts del clúster"
com.vmware.vsan.fileservice.fault.reconfiguresharefailure ="No se pudo reconfigurar el recurso compartido de archivos"
com.vmware.vsan.fileservice.fault.queryfileservicedomains = "No se pudieron consultar los dominios del servicio de archivos"
com.vmware.vsan.fileservice.fault.shareconfigerror = "Se proporcionó una configuración de recurso compartido no válida"
com.vmware.vsan.fileservice.fault.remounterror = "Error al volver a montar recursos compartidos del servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.invalidaffinity = "La ubicación de afinidad '{affinity}' no es válida."
com.vmware.vsan.fileservice.fault.ipconfig.atleastoneip= "Se debe especificar al menos una dirección IP para la dirección del servidor de archivos"
com.vmware.vsan.fileservice.fault.ipconfig.mixediptype = "No se admite la configuración mixta: IPv4 + IPv6"
com.vmware.vsan.fileservice.fault.ipconfig.iptypenotsame = "El tipo de IP no es el mismo que la dirección DNS"
com.vmware.vsan.fileservice.fault.ipconfig.noipaddress = "No se especificó la dirección IP para un servidor de archivos"
com.vmware.vsan.fileservice.fault.ipconfig.nosubnetmask = "No se especificó la máscara de subred IP para un servidor de archivos"
com.vmware.vsan.fileservice.fault.ipconfig.noprefixlength = "No se especificó el campo de longitud de prefijo para un servidor de archivos IPv6"
com.vmware.vsan.fileservice.fault.ipconfig.prefixlengthmustsame = "Todas las longitudes de prefijo deben ser las mismas"
com.vmware.vsan.fileservice.fault.ipconfig.nogateway = "No se especificó la puerta de enlace IP para un servidor de archivos"
com.vmware.vsan.fileservice.fault.ipconfig.subnetmaskmustsame = "Todas las máscaras de subred IP deben ser las mismas"
com.vmware.vsan.fileservice.fault.ipconfig.notinsamesubnet = "Todas las IP deben estar en la misma subred"
com.vmware.vsan.fileservice.fault.ipconfig.invalidgateway = "La puerta de enlace debe estar en la misma subred para {ip}"
com.vmware.vsan.fileservice.fault.ipconfig.onegateway = "Todas las puertas de enlace de IP deben ser las mismas. Se encontraron al menos dos puertas de enlace de IP: {gateway} y {ipgateway}"
com.vmware.vsan.fileservice.fault.ipconfig.oneprimaryip = "Solo se admite una IP principal. Se encontraron al menos dos direcciones IP principales: {ip} y {pip}"
com.vmware.vsan.fileservice.fault.ipconfig.samednssudomain = "Todos los servidores de archivos deben estar en el mismo subdominio DNS para el clúster normal"
com.vmware.vsan.fileservice.fault.ipconfig.duplicatedip = "Se encontraron direcciones IP duplicadas en el campo ipAddress"
com.vmware.vsan.fileservice.fault.ipconfig.duplicatedfqdn = "Se encontraron FQDN duplicados"
com.vmware.vsan.fileservice.fault.ipconfig.fqdnnotmatchip = "El número de direcciones IP y de FQDN únicos no coinciden"
com.vmware.vsan.fileservice.fault.ipconfig.noprimaryip = "El grupo de direcciones IP del servidor de archivos requiere una IP principal"
com.vmware.vsan.fileservice.fault.ipconfig.sameprimarydnsdomain = "El nombre de dominio DNS principal del servidor de archivos debe ser el mismo que el nombre de dominio AD."
com.vmware.vsan.fileservice.fault.ipconfig.fqdnnotindnssuffixes = "El sufijo del FQDN del servidor de archivos debe estar en la lista de sufijos DNS."
com.vmware.vsan.fileservice.fault.ipconfig.addomainnamenotindnssuffixes = "El nombre de dominio AD o el nombre de dominio DNS principal deben estar en la lista de sufijos DNS."
com.vmware.vsan.fileservice.fault.fqdn.toolong = "El FQDN proporcionado debe ser un nombre de host válido que no supere los 255 caracteres: '{fqdn}' no es válido"
com.vmware.vsan.fileservice.fault.fqdn.invalidchar = "El FQDN no debe incluir marcas de puntuación ni espacios en blanco excepto '-.,', '{fqdn}' no es válido"
com.vmware.vsan.fileservice.fault.fqdn.invalidend= "El nombre de FQDN no es válido: '{fqdn}', no debe comenzar ni terminar con - o ."
com.vmware.vsan.fileservice.fault.fqdn.numstart= "El nombre de FQDN no es válido: '{fqdn}', no debe comenzar ni terminar con un dígito"
com.vmware.vsan.fileservice.fault.fqdn.invalidform = "El FQDN debe tener el formato siguiente: mac1.exmpdomain.com o mac1.subdom1.exmpdomain.com: '{fqdn}'"
com.vmware.vsan.fileservice.fault.fqdn.componentoolong = "Cada componente de FQDN debe tener un máximo de 63 caracteres: '{fqdn}'"
com.vmware.vsan.fileservice.fault.fqdn.componentooshort = "Cada componente de FQDN debe tener un mínimo de 2 caracteres: '{fqdn}'"
com.vmware.vsan.fileservice.fault.fqdn.invalidnetbiosname = "La primera parte del FQDN (también conocida como NetBIOS) debe tener un máximo de 15 caracteres: '{fqdn}'"
com.vmware.vsan.fileservice.fault.fqdn.nofqdn = "No se proporcionó ningún FQDN"
com.vmware.vsan.fileservice.fault.networkpartition = "Se detectaron particiones de red: {hosts}"
com.vmware.vsan.fileservice.fault.ntpnotenabled = "El servicio NTP no está habilitado en los hosts: {hosts}, por lo que es posible que la hora del servidor de archivos no se sincronice con el servidor de AD, lo que puede provocar un error al crear el dominio de AD"
com.vmware.vsan.fileservice.fault.ntpunknown = "No se pudo obtener la información de configuración de NTP en los hosts: {hosts}"
com.vmware.vsan.fileservice.fault.timedrift = "La desviación horaria entre VC y el host ESXi es superior a 60s en los hosts: {hosts}"
com.vmware.vsan.fileservice.fault.vsandisabledonhost = "Se detectaron hosts con vSAN deshabilitado: {hosts}"
com.vmware.vsan.fileservice.fault.nodnsserver = "Se debe proporcionar la dirección del servidor DNS para el dominio: {domainName}"
com.vmware.vsan.fileservice.fault.mixeddnsiptype = "No se admite el tipo de IP mixto en la lista de servidores DNS del dominio: {domainName}"
com.vmware.vsan.fileservice.fault.invaliddns = "Las direcciones IP del servidor DNS: {invalidDnsIPs} no son válidas"
com.vmware.vsan.fileservice.fault.nodnssuffix = "Se deben proporcionar los sufijos DNS para el dominio: {domainName}"
com.vmware.vsan.fileservice.fault.dnssuffixformaterror = "Los sufijos DNS: {invalidDnsSuffixes} no son válidos"
com.vmware.vsan.fileservice.fault.noipconfig = "Se debe proporcionar FileServerIpConfig para el dominio: {domainName}"
com.vmware.vsan.fileservice.fault.invaliddnssuffix = "La lista de sufijos DNS debe incluir el sufijo FQDN del servidor de archivos"
com.vmware.vsan.fileservice.fault.invaliddvs = "Versión de DVS: la versión {version} de DVS no es compatible, debe ser posterior a la versión 6.6.0"
com.vmware.vsan.fileservice.fault.dvsnotfound = "No se puede encontrar {network} de DVS"
com.vmware.vsan.fileservice.fault.novsandatastore = "Los siguientes hosts no tienen ningún almacén de datos de vSAN: {hosts}"
com.vmware.vsan.fileservice.fault.nodiskgroup = "Los siguientes hosts no tienen el grupo de discos: {hosts}"
com.vmware.vsan.fileservice.fault.upgradefsvm = "No se pudo actualizar la máquina virtual del servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.configconvertionerror = "No se pudo convertir el formato del archivo de configuración del servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.reconfigureditfailure = "No se pudo establecer el servicio de archivos de vSAN mediante el estado de cifrado de cableado"
com.vmware.vsan.fileservice.fault.triggerrebalance = "No se pudo activar la redistribución del servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.notvalidouformat = "No se pudo analizar el nombre de la unidad organizativa. Utilice el nombre distintivo de la unidad organizativa."
com.vmware.vsan.fileservice.fault.checkrebalancefailure = "No se pudo comprobar la información de equilibrio de servidores de archivos"
com.vmware.vsan.fileservice.fault.containercreationfailures.adconfigissue.failedtoreachdc = " No se puede establecer la conexión con el servidor de AD a partir de la información de la configuración de dominio de FS. Este problema puede deberse a uno de los siguientes problemas: 1. Las configuraciones del firewall son incorrectas. Compruebe la lista de puertos de servidor abiertos en el siguiente vínculo: https://support.microsoft.com/es-es/help/179442/how-to-configure-a-firewall-for-domains-and-trusts 2. No se puede resolver el nombre DNS del dominio de AD con la información configurada para el servidor DNS y el sufijo DNS. 3. No se puede acceder a la red de AD desde la red del servidor de archivos."
com.vmware.vsan.fileservice.fault.containercreationfailures.adconfigissue.clockskew = "La diferencia horaria entre el servidor de AD y la hora del sistema local es demasiado grande. Asegúrese de que su AD esté sincronizado con un origen de hora válido, como un servidor NTP. Utilice el mismo servidor NTP introducido en la configuración del clúster de vSAN."
com.vmware.vsan.fileservice.fault.containercreationfailures.adconfigissue.invalidpassword = "Nombre de usuario o contraseña no válidos para la configuración de AD."
com.vmware.vsan.fileservice.fault.containercreationfailures.adconfigissue.notenoughperm = "El usuario no tiene los permisos necesarios en esta unidad organizativa. Si no se introduce ninguna unidad organizativa, el sistema intentará registrar estos servidores de archivos con los equipos de unidad organizativa predeterminados. El usuario debe tener los siguientes permisos: 1. Crear y eliminar objetos del equipo. 2. Leer y escribir ms-DS-PrincipleName. 3. Leer y escribir uPNSuffixes."
com.vmware.vsan.fileservice.fault.containercreationfailures.unknownerror = "Se produjo un error en la creación del servidor de archivos debido a un motivo desconocido. Póngase en contacto con el equipo de soporte de VMware para obtener más información"
com.vmware.vsan.fileservice.fault.containercreationfailures.adconfigissue.noou = "La unidad organizativa introducida no existe."
com.vmware.vsan.fileservice.fault.containercreationfailures.adconfigissue.invalidadconfig = "Parece que hay un problema con la configuración de AD. Póngase en contacto con el soporte de VMware para obtener más información."
com.vmware.vsan.fileservice.fault.querysnapshotfailure = "No se pudieron consultar las instantáneas de recursos compartido de archivos de vSAN."
com.vmware.vsan.fileservice.fault.createsnapshotfailure = "No se pudo crear la instantánea de recursos compartidos de archivos de vSAN."
com.vmware.vsan.fileservice.fault.removesnapshotfailure = "No se pudo quitar la instantánea de recursos compartidos de archivos de vSAN."
com.vmware.vsan.fileservice.fault.upgradefsonhostfailure = "No se pudo actualizar el servicio de archivos en el host."
com.vmware.vsan.fileservice.fault.upgradeforsnapfailure = "No se pudo actualizar la función de instantáneas en el host."
com.vmware.vsan.fileservice.fault.upgradesmbconfigfailure = "No se pudo actualizar para los archivos de configuración de SMB"
com.vmware.vsan.fileservice.fault.upgradefortreedeletefailure = "No se pudo actualizar la función de borrado de árbol asíncrono en el host."
com.vmware.vsan.fileservice.fault.scnotsupported= "No se admite el clúster ampliado"
com.vmware.vsan.fileservice.fault.scnotenabled= "El clúster ampliado aún no está habilitado"
com.vmware.vsan.fileservice.fault.epicnotrunning = "No se admite la comprobación avanzada de configuración de dominio cuando EPiC no se está ejecutando"
com.vmware.vsan.fileservice.fault.fsvmnothealthy = "No se admite la comprobación avanzada de configuración de dominio cuando la FSVM no está en buen estado"
com.vmware.vsan.fileservice.fault.preflight.advchecknotsupport = "La comprobación avanzada de configuración de dominio solo se admite a partir de la versión 8.0 del servicio de archivos de vSAN"
com.vmware.vsan.fileservice.fault.preflight.reconfignotallowed = "No se permite cambiar la configuración de AD junto con otras configuraciones. Puede realizar la reconfiguración dos veces para cambiar todas las configuraciones."
com.vmware.vsan.fileservice.fault.preflight.aderror = "No se pudieron obtener las direcciones IP de los controladores de dominio a través del servidor DNS"
com.vmware.vsan.fileservice.fault.preflight.wrongpassword = "No se pudo autenticar en el servidor de AD debido a una contraseña no válida"
com.vmware.vsan.fileservice.fault.preflight.wronguser = " No se pudo autenticar en el servidor de AD debido a un nombre de usuario no válido"
com.vmware.vsan.fileservice.fault.preflight.wrongrealm = "No se pudo autenticar en el servidor de AD debido a un dominio no válido"
com.vmware.vsan.fileservice.fault.preflight.realmnotmatch = "No se pudo autenticar en el servidor de AD porque el dominio no coincide"
com.vmware.vsan.fileservice.fault.preflight.adcredentialunknown = "No se pudo autenticar en el servidor de AD"
com.vmware.vsan.fileservice.fault.preflight.unreachable = "No se puede acceder a la puerta de enlace del servidor de archivos principal"
com.vmware.vsan.fileservice.fault.preflight.gatewayunknown = "Error en la comprobación de conectividad de la puerta de enlace"
com.vmware.vsan.fileservice.fault.preflight.dnsippoolissue= "Error al buscar DNS {type} en los nombres de consulta {host} (servidor DNS: {dns})"
com.vmware.vsan.fileservice.fault.preflight.unaccessports = "No se pudo conectar al puerto {port} de {service} a través de TCP en el host {host}"
com.vmware.vsan.fileservice.fault.preflight.querynetbioserror = "No se pudo consultar el nombre de NetBIOS del dominio en los hosts {hosts}. Un posible motivo: el puerto UDP (389) del servidor de AD no está abierto"
com.vmware.vsan.fileservice.fault.preflight.timeout = "Se agotó el tiempo de espera de comprobación de {checkType}"
com.vmware.vsan.fileservice.fault.preflight.advexception = "No se pudo comprobar la configuración del dominio: {ex}"
com.vmware.vsan.health.msg.exceedqueryobjects = "Se ha superado el número máximo de objetos de consulta permitido (es decir, {number})"
com.vmware.vsan.capabilities.msg.rdmacapablenic = "Los hosts del clúster no tienen ninguna NIC con capacidad de RDMA: {host}"
com.vmware.vsan.objectservice.msg.relayoutobjectsfailed = "Error en el objeto de retransmisión. Código de error: ({err})"
com.vmware.vsan.objectservice.msg.relayoutobject.inprogress = "Ya se está ejecutando una tarea RelayoutObject."
com.vmware.vsan.objectservice.msg.relayoutobject.timeout = "Se agotó el tiempo de espera de la tarea RelayoutObject porque no hubo actualizaciones de la entrada cmmds durante {min} minutos."
com.vmware.vsan.hardwaremgmt.fault.vsandisabled = "vSAN no está habilitado en el host."
com.vmware.vsan.hardwaremgmt.fault.nocapability = "No se encuentra la capacidad de administración de hardware en el host."
com.vmware.vsan.hardwaremgmt.fault.queryerror = "No se pudo consultar el resumen de hardware. Compruebe los registros para obtener más detalles."
com.vmware.vsan.hardwaremgmt.fault.setledstate = "No se pudo establecer el estado de LED para el disco {disk} en el host {host} porque {reason}"
com.vmware.vsan.hardwaremgmt.fault.invalidilocredentials = "Falta las credenciales de iLO o no son válidas. Configure credenciales de iLO válidas."
com.vmware.vsan.hardwaremgmt.fault.vnicnotconfigured = "El host no admite la configuración de la NIC virtual de HPE. Compruebe si la NIC virtual está habilitada."
com.vmware.vsan.hardwaremgmt.fault.vnicmissinguplink = "No se pudo consultar el resumen de hardware. Compruebe si el vínculo superior del dispositivo 'vusb0' falta en un conmutador virtual existente."
# Task error message for async API QueryClusterHealthSummaryTask
com.vmware.vsan.health.fault.invalidtask = "Tarea no válida {task}."
com.vmware.vsan.health.fault.taskfailed = "La tarea {task} no se está ejecutando o no se completó correctamente."
com.vmware.vsan.health.fault.invalidspec = "Capacidad de SPBM no admitida: {caps}. Tipo de destino no admitido: {types}."
com.vmware.vsan.health.fault.invalidregulation = "La regulación proporcionada {reg} no es válida."
# The error message for the health reconfigure process
com.vmware.vsan.health.fault.threshold.outofrange = "El umbral no es superior a 0 o supera los 100 para {target}."
com.vmware.vsan.health.fault.threshold.largeryellowthreshold = "El umbral amarillo de la comprobación de estado supera el umbral rojo para {target}."
com.vmware.vsan.health.fault.threshold.targetmissing = "Falta el umbral de comprobación de estado objetivo."
com.vmware.vsan.health.fault.threshold.duptarget = "Destinos duplicados en la configuración del umbral de estado de vSAN."
# The error message for the vcg notification service
com.vmware.vsan.health.fault.vcgnotification.spec.invalidemail = "El correo electrónico proporcionado {email} no es válido."
# The error message for File Analytics
com.vmware.vsan.fileservice.fault.configurefileanalyticsfail = "No se pudo configurar el análisis de archivos"
com.vmware.vsan.fileanalytics.enable.error = "Error al habilitar el análisis de archivos"
com.vmware.vsan.fileanalytics.disable.error = "Error al deshabilitar el análisis de archivos"
com.vmware.vsan.fileanalytics.consume.error = "Error durante el consumo de datos de análisis de archivos"
com.vmware.vsan.fileanalytics.consume.lockissue = "La tarea de consumo de análisis de archivos está funcionando activada por el back-end"
com.vmware.vsan.fileanalytics.consume.invalid = "El host no está cualificado para consumir datos de Análisis de archivos"
# The error message for Data Protection Service
com.vmware.dp.fault.dpsrestarted = "Se reinició el servicio de protección de datos (DPS)"
com.vmware.dp.fault.coldmigrationinprogress = "La operación de protección de datos no está permitida mientras haya una migración en frío en curso"
com.vmware.dp.fault.dpsfault = "El servicio de protección de datos (DPS) encontró un error"
com.vmware.dp.fault.dpdthrottlelimitexceeded = "Demasiadas solicitudes simultáneas al daemon de protección de datos (DPD)"
com.vmware.dp.fault.snapshotinprogress = "Ya hay una instantánea en curso"
com.vmware.dp.fault.invalidsnapshottype = "El tipo de instantánea no es válido para la entidad protegida"
com.vmware.dp.fault.quiescefailure = "Error al poner en modo inactivo"
com.vmware.dp.fault.invaliddisk = "La entidad protegida hace referencia a una clave de disco no válida"
com.vmware.dp.fault.unsupporteddisk = "La entidad protegida hace referencia a un tipo de disco no admitido para LWD"
com.vmware.dp.fault.snapshotnotfound = "La diapositiva no existe"
com.vmware.dp.fault.enableprotectionservicesfault = "No se pudieron habilitar los servicios de protección"
com.vmware.dp.fault.syncinprogress = "Ya hay una operación de sincronización en curso"
com.vmware.dp.fault.restoreinprogress = "Ya hay una operación de restauración en curso"
com.vmware.dp.fault.invalidsynctype = "El tipo de sincronización especificado es incorrecto"
com.vmware.dp.fault.invalidsnapshot = "No se pueden determinar los cambios relativos para la instantánea dada"
com.vmware.dp.fault.invalidsource = "El origen especificado no es válido o no está disponible"
com.vmware.dp.fault.cancelsnapshotrequired = "La instantánea actual no es válida y debe reintentarse"
com.vmware.dp.fault.fullsyncrequired = "Se requiere una sincronización completa"
com.vmware.dp.fault.snapshottransportfault = "No se pudieron transportar los datos de la instantánea"
com.vmware.dp.fault.pealreadyclaimed = "Otro proveedor ya inició una operación en la entidad protegida"
com.vmware.dp.fault.dpsbusy = "El servicio de protección de datos (DPS) está ocupado. Debe volver a intentar la operación después de un intervalo"
com.vmware.dp.fault.diskclosing = "Se cerró un disco durante la operación. Esto puede ocurrir debido a eventos del ciclo de vida de la máquina virtual, como el apagado de máquinas virtuales, vMotion y la conmutación por error de HA. Se debe volver a intentar la operación"
com.vmware.dp.fault.pepartiallyprotected = "La entidad protegida contiene discos protegidos y sin protección"
com.vmware.dp.fault.peincompleterequest = "La operación se intentó en un subconjunto de discos de la instantánea"
com.vmware.dp.fault.operationinterrupted = "La operación se canceló debido a una interrupción inesperada. Se debe volver a realizar la operación"
com.vmware.dp.fault.dpdconnectionlost = "No se puede conectar al daemon de protección de datos (DPD)"
com.vmware.dp.fault.basesnapshotmismatch = "La instantánea base especificada no coincide con la instantánea más reciente de los discos en la entidad protegida"
com.vmware.dp.fault.pebusy = "La entidad protegida especificada ya está realizando una operación de protección o desprotección"
com.vmware.dp.fault.vendoridinconsistent = "Hay un error de coincidencia de vendorId entre los discos de la entidad protegida"
com.vmware.dp.fault.migrationinprogress = "La operación de protección de datos no está permitida mientras haya una migración en curso"
com.vmware.vsan.fileanalytics.performclusterscan.error = "No se pudo realizar la exploración del recurso compartido de archivos del clúster por el siguiente motivo: {reason}."
# The error message for historical health
com.vmware.vsan.health.fault.historicalhealth.spec.invalidtime = "La hora de finalización no puede ser anterior a la hora de inicio."
com.vmware.vsan.health.fault.historicalhealth.spec.invalidid.prefix = "groupId y testId deben tener el prefijo 'com.vmware.vsan.health.test.'."
com.vmware.vsan.health.fault.historicalhealth.spec.invalidid.together = "groupId y testId deben proporcionarse juntos."
com.vmware.vsan.health.fault.historicalhealth.db.connectionerror = "No se pudo conectar a la base de datos."
# The error message for VCG notification service
com.vmware.vsan.vcgnotification.fault.queryerror = "No se pudo consultar la información de suscripción de la VCG (Guía de compatibilidad de VMware) porque: {reason}."
com.vmware.vsan.vcgnotification.noenabledcluster = "No se encontró ningún clúster con el servicio de notificación de la VCG (Guía de compatibilidad de VMware) de vSAN habilitado."
com.vmware.vsan.vcgnotification.networkissue = "No hay conexión a Internet."
com.vmware.vsan.vcgnotification.fault.vsandisabled = "vSAN no está habilitado en el clúster {cluster}."
com.vmware.vsan.vcgnotification.fault.configuration = "No se pudo configurar el servicio de notificación de la VCG (Guía de compatibilidad de VMware) de vSAN en el clúster {cluster} porque: {reason}."
com.vmware.vsan.vcgnotification.fault.invalidparam = "No se proporcionó ningún clúster en la especificación de configuración de VCG {spec}."
com.vmware.vsan.vcgnotification.fault.pendingemailupdate = "No se pudo actualizar el correo electrónico porque hay una tarea pendiente. Compruebe la conexión a Internet e inténtelo de nuevo más tarde."
com.vmware.vsan.vcgnotification.fault.vvsapifailure = "No se pudo llamar a la API de VCG externa. Compruebe el registro de vSAN Health Service para obtener más información."
# Diagnostics
com.vmware.vsan.diag.fault.iodiag.invalidduration = "Se proporcionó la duración de diagnóstico no válida {duration}. El rango de duración válido es {min} - {max} segundos."
com.vmware.vsan.diag.fault.iodiag.invalidtargets = "Solo se puede ejecutar el diagnóstico en una máquina virtual."
com.vmware.vsan.diag.fault.iodiag.invalidtarget = "No se proporcionó el objeto de destino."
com.vmware.vsan.diag.fault.iodiag.invalidtarget.type = "El tipo de objeto de destino {type} no es compatible."
com.vmware.vsan.diag.fault.iodiag.invalidtarget.owner = "La máquina virtual de destino '{vm}' no está alojada en el clúster '{cluster}'"
com.vmware.vsan.diag.fault.iodiag.invalidtarget.notfound = "El identificador de entidad '{vm}' no encuentra el destino."
com.vmware.vsan.diag.fault.iodiag.invalidobjuuids = "El analizador de recorrido de E/S encontró UUID de objetos de destino no válidos: {uuids}"
com.vmware.vsan.diag.fault.iodiag.invalidobjuuids.fcdcns.notsupport = "No se admite el analizador de recorrido de E/S para los UUID de objetos de destino: {uuids} que son objetos de volumen FCD o CNS."
com.vmware.vsan.diag.fault.iodiag.invalidobjuuids.inaccessible = "El analizador de recorrido de E/S encontró UUID de objetos de destino inaccesibles: {uuids}"
com.vmware.vsan.diag.fault.iodiag.missedcluster = "Falta el parámetro del clúster."
com.vmware.vsan.diag.fault.iodiag.perfsvcdisabled = "El servicio de rendimiento de vSAN está deshabilitado. Habilite esta opción antes de realizar cualquier operación de diagnóstico."
com.vmware.vsan.diag.fault.iodiag.vsandisabled = "No se admite la operación porque vSAN no está habilitado para el clúster '{cluster}'."
com.vmware.vsan.diag.fault.iodiag.taskrunning = "El sistema no admite el inicio de una tarea del analizador de recorrido de E/S en el clúster '{cluster}' que ya tiene una tarea en ejecución."
com.vmware.vsan.diag.fault.iodiag.internalerror = "Error interno del analizador de recorrido de E/S."
com.vmware.vsan.diag.fault.iodiag.hosttaskcancelled = "Se canceló la tarea del analizador de recorrido de E/S."
com.vmware.vsan.diag.fault.iodiag.stretchedcluster.notsupport = "El analizador de recorrido de E/S no se admite en el clúster ampliado."
com.vmware.vsan.diag.fault.iodiag.nestedfaultdomain.notsupport = "El analizador de recorrido de E/S no se admite en la configuración de clústeres con dominio de errores anidado."
com.vmware.vsan.diag.fault.iodiag.computeonlycluster.notsupport = "El analizador de recorrido de E/S no se admiten en el clúster de solo cómputo de malla HCI."
com.vmware.vsan.diag.fault.iodiag.vmnotpoweredon.notsupport = "La máquina virtual de destino '{vm}' no está encendida."
com.vmware.vsan.diag.fault.iodiag.vmnotconnected.notsupport = "La máquina virtual de destino '{vm}' no está conectada."
com.vmware.vsan.diag.fault.iodiag.remotevsanobject.notsupport = "No se admite el analizador de recorrido de E/S para los UUID de objetos de destino: {uuids} que se encuentran en el almacén de datos remoto."
com.vmware.vsan.diag.fault.iodiag.novsanobject = "El objeto de destino no tiene ningún objeto de vSAN que diagnosticar."
com.vmware.vsan.diag.fault.iodiag.general.error = "Se produjo un error general durante la comprobación previa del analizador de recorrido de E/S."
com.vmware.vsan.diag.fault.iodiag.cluster.nocapabilities = "El clúster '{cluster}' no tiene la capacidad del analizador de recorrido de E/S."
com.vmware.vsan.diag.fault.iodiag.hosts.nocapabilities = "Los siguientes host(s) no tienen la capacidad del analizador de recorrido de E/S: '{hosts}'"
# Cluster shutdown
com.vmware.vsan.clustershutdown.fault.poweronvmsfound = "Se encontraron máquinas virtuales no apagadas."
